name: Deploy to EC2

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Setup SSH
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        
        - name: Deploy App to EC2
          run: |
            ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
              sudo apt update -y
              sudo apt install -y git python3-pip python3-venv curl

              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt install -y nodejs

              if [ ! -d flask-cicd-app ]; then
                git clone https://github.com/Birarvindersingh/flask-cicd-app.git
              fi
              cd flask-cicd-app && git pull

              python3 -m venv venv
              source venv/bin/activate

              pip install -r requirements.txt

              sudo npm install -g pm2

              pm2 delete flask-app || true
              pm2 start venv/bin/python -- app.py --name flask-app
              pm2 save
            EOF